version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3001:3001"
    command: uvicorn app:app --host 0.0.0.0 --port 3001 --log-level debug --reload
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    networks:
      - backendnetwork
networks:
  backendnetwork:
    external: true
