name: AI Build Docker Image

on:
  workflow_call:
    inputs:
      target_env:
        description: "The target environment to build the docker image for. Possible values are `branch`, `stage` or `prod`"
        required: true
        type: string
      target_app:
        description: "The target backend app to build the docker image for. Possible values are `engine`, `server`, or `slackbot`"
        required: true
        type: string
      image_tag:
        description: "The image tag"
        required: true
        type: string

    outputs:
      docker_image:
        description: "Docker image"
        value: ${{ jobs.build-docker-image.outputs.docker_image }}

env:
  ECR_REPOSITORY: ai-${{ inputs.target_app }}-${{ inputs.target_env }}

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    outputs:
      docker_image: ${{ steps.build-image.outputs.docker_image }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: true

      - name: Use Node.js
        if: inputs.target_app == 'slackbot'
        uses: actions/setup-node@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          if [ ${{ inputs.target_app }} == "engine" ]; then
            echo Build engine
            git submodule init
            git submodule update
            cd apps/ai/server/dataherald
            ls
          elif [ ${{ inputs.target_app }} == "server" ]; then
            echo Build server
            cd apps/ai/server
          elif [ ${{ inputs.target_app }} == "slackbot" ]; then
            echo Build slackbot
            cd apps/ai/clients/slack
            npm install -g pnpm
            pnpm install
          fi
          echo Building Dockerfile
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "docker_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
