name: AI Check Repository Changes

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string
        description: "The environment to check changes for. Possible values are: `stage`, `prod`"
    outputs:
      engine_changed:
        description: "Whether the engine has changed"
        value: ${{ jobs.set-changes.outputs.engine_changed }}
      server_changed:
        description: "Whether the server has changed"
        value: ${{ jobs.set-changes.outputs.server_changed }}
      slackbot_changed:
        description: "Whether the slackbot has changed"
        value: ${{ jobs.set-changes.outputs.slackbot_changed }}
      console_changed:
        description: "Whether the console has changed"
        value: ${{ jobs.set-changes.outputs.console_changed }}

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      engine_changed: ${{ steps.filter_engine.outputs.engine }}
      server_changed: ${{ steps.filter_server.outputs.server }}
      slackbot_changed: ${{ steps.filter_slackbot.outputs.slackbot }}
      console_changed: ${{ steps.filter_console.outputs.console }}
    steps:
      - uses: actions/checkout@v4

      - id: filter_engine
        uses: dorny/paths-filter@v3
        with:
          filters: |
            engine:
            - '.github/workflows/ai-deploy-${{ inputs.target_env }}-env.yml'
            - 'apps/ai/server/.aws/task-definition-${{ inputs.target_env }}.json'
            - 'apps/ai/server/main.tf'
            - 'apps/ai/server/dataherald/**'

      - id: filter_server
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
            - '.github/workflows/ai-deploy-${{ inputs.target_env }}-env.yml'
            - 'apps/ai/server/.aws/task-definition-${{ inputs.target_env }}.json'
            - 'apps/ai/server/main.tf'
            - 'apps/ai/server/**'

      - id: filter_slackbot
        uses: dorny/paths-filter@v3
        with:
          filters: |
            slackbot:
            - '.github/workflows/ai-deploy-${{ inputs.target_env }}-env.yml'
            - 'apps/ai/clients/slack/.aws/task-definition-${{ inputs.target_env }}.json'
            - 'apps/ai/clients/slack/**'

      - id: filter_console
        uses: dorny/paths-filter@v3
        with:
          filters: |
            console:
            - '.github/workflows/ai-deploy-${{ inputs.target_env }}-env.yml'
            - 'apps/ai/clients/admin-console/**'
  set-changes:
    needs: check-changes
    runs-on: ubuntu-latest
    outputs:
      engine_changed: ${{ steps.set-outputs.outputs.engine_changed }}
      server_changed: ${{ steps.set-outputs.outputs.server_changed }}
      slackbot_changed: ${{ steps.set-outputs.outputs.slackbot_changed }}
      console_changed: ${{ steps.set-outputs.outputs.console_changed }}
    steps:
      - name: Set Changes Outputs
        id: set-outputs
        run: |
          if [ ${{ inputs.target_env }} == "stage" ]; then
            echo Setting changes outputs for stage
            echo "engine_changed=${{ needs.check-changes.outputs.engine_changed }}" >> $GITHUB_OUTPUT
            echo "server_changed=${{ needs.check-changes.outputs.server_changed }}" >> $GITHUB_OUTPUT
            echo "slackbot_changed=${{ needs.check-changes.outputs.slackbot_changed }}" >> $GITHUB_OUTPUT
            echo "console_changed=${{ needs.check-changes.outputs.console_changed }}" >> $GITHUB_OUTPUT
          else
            echo Setting changes outputs for prod -- all true
            echo "engine_changed=true" >> $GITHUB_OUTPUT
            echo "server_changed=true" >> $GITHUB_OUTPUT
            echo "slackbot_changed=true" >> $GITHUB_OUTPUT
            echo "console_changed=true" >> $GITHUB_OUTPUT
          fi
