name: AI Deploy PROD Environment

on:
  push:
    tags:
      - v*.**
    paths:
      - ".github/workflows/ai-deploy-prod-env.yml" # this file
      - ".github/workflows/ai-deploy-env.yml"
      - ".github/workflows/ai-build-docker.yml"
      - ".github/workflows/ai-deploy-docker-ecs.yml"
      - ".github/workflows/ai-deploy-frontend.yml"
      - "apps/ai/**"
      - "!**/.env.example"
      - "!**/README.md"

jobs:
  deploy-env:
    name: Prod
    uses: ./.github/workflows/ai-deploy-env.yml
    with:
      target_env: prod
    secrets:
      SUBMODULE_UPDATE_TOKEN: ${{secrets.SUBMODULE_UPDATE_TOKEN}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      GH_SLACK_WEBHOOK_URL: ${{secrets.GH_SLACK_WEBHOOK_URL}}
      VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
      VERCEL_AI_CONSOLE_PROJECT_ID: ${{secrets.VERCEL_AI_CONSOLE_PROJECT_ID}}
      VERCEL_ACCESS_TOKEN: ${{secrets.VERCEL_ACCESS_TOKEN}}
