name: AI Deploy STAGE Environment

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ai-deploy-stage-env.yml

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      engine_changed: ${{ steps.filter_engine.outputs.engine }}
      server_changed: ${{ steps.filter_server.outputs.server }}
      slackbot_changed: ${{ steps.filter_slackbot.outputs.console }}
      console_changed: ${{ steps.filter_console.outputs.console }}
    steps:
      - uses: actions/checkout@v4

      - id: filter_engine
        uses: dorny/paths-filter@v3
        with:
          filters: |
            engine:
              - '.github/workflows/ai-server-dataherald-stage.yml'
              - 'apps/ai/server/dataherald/**'

      - id: filter_server
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
              - '.github/workflows/ai-server-stage.yml'
              - 'apps/ai/server/**'

      - id: filter_slackbot
        uses: dorny/paths-filter@v3
        with:
          filters: |
            console:
              - '.github/workflows/ai-slackbot-stage.yml'
              - 'apps/ai/clients/slack/**'

      - id: filter_console
        uses: dorny/paths-filter@v3
        with:
          filters: |
            console:
              - '.github/workflows/ai-console-stage.yml'
              - 'apps/ai/clients/admin-console/**'

  deploy-engine:
    name: Deploy Engine
    needs: check-changes
    if: needs.check-changes.outputs.engine_changed == 'true'
    uses: ./.github/workflows/ai-server-dataherald-stage.yml

  deploy-server:
    name: Deploy Server
    needs: [check-changes, deploy-engine]
    if: needs.check-changes.outputs.server_changed == 'true' && success()
    uses: ./.github/workflows/ai-server-stage.yml

  deploy-slackbot:
    name: Deploy Slackbot
    needs: [check-changes, deploy-server]
    if: needs.check-changes.outputs.slackbot_changed == 'true' && success()
    uses: ./.github/workflows/ai-slackbot-stage.yml

  deploy-console:
    name: Deploy Console
    needs: [check-changes, deploy-server]
    if: needs.check-changes.outputs.console_changed == 'true' && success()
    uses: ./.github/workflows/ai-console-stage.yml
