name: AI Deploy Branch Environment

on:
  workflow_dispatch:
    inputs:
      option:
        description: "Select Initial Database (if DB already exists this will be dismissed)"
        required: true
        type: choice
        options:
          - "stage"
          - "sample"
          - "empty"

env:
  ECR_CORE_REPOSITORY: ai-engine-branch
  ECR_SERVER_REPOSITORY: ai-server-branch
  SLACK_ICON: https://files.dataherald.com/random/github-actions.png
  SLACK_USERNAME: GitHub Actions
  SLACK_CHANNEL: eng-notifications
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}

jobs:
  extract-branch-names:
    name: Setup Names From Branch
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
      branch_name: ${{ steps.extract_branch.outputs.branch_name }}
      db_name: ${{ steps.extract_branch.outputs.db_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          formatted_branch=$(echo "$branch" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]/-/g')
          db_name=branch-$formatted_branch

          RESOURCE_NAME_LENGHT=32

          # Terraform resources name lenght limit is 32
          # MongoDB database name length limit is 38
          formatted_branch=${formatted_branch:0:$RESOURCE_NAME_LENGHT}
          db_name=${db_name:0:$RESOURCE_NAME_LENGHT} 

          # Ensure the last character is alphanumeric 
          # Pinecone doesn't allow special characters for the last character
          while [[ ! ${formatted_branch: -1} =~ [a-zA-Z0-9] ]]; do
            formatted_branch=${formatted_branch:0:-1}
          done

          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "branch_name=$formatted_branch" >> $GITHUB_OUTPUT
          echo "db_name=$db_name" >> $GITHUB_OUTPUT

  start-self-hosted-runner:
    name: Start self-hosted EC2 runner
    uses: ./.github/workflows/ai-start-self-hosted-runner.yml
    secrets: inherit

  build-engine:
    name: Build Engine
    needs: extract-branch-names
    uses: ./.github/workflows/ai-build-docker.yml
    secrets: inherit
    with:
      target_app: engine
      target_env: branch
      image_tag: ${{ needs.extract-branch-names.outputs.branch_name}}-${{ github.sha }}

  build-server:
    name: Build Server
    needs: extract-branch-names
    uses: ./.github/workflows/ai-build-docker.yml
    secrets: inherit
    with:
      target_app: server
      target_env: branch
      image_tag: ${{ needs.extract-branch-names.outputs.branch_name}}-${{ github.sha }}

  deploy-backend:
    name: Deploy Backend infrastructure
    needs: [extract-branch-names, build-engine, build-server]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/ai/server/terraform/branch
    outputs:
      api_url: ${{ steps.get-api-url.outputs.api_url }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Apply Terraform
        env:
          TF_VAR_sha: ${{ github.sha }}
          TF_VAR_branch_name: ${{ needs.extract-branch-names.outputs.branch_name }}
          TF_VAR_vpc_id: ${{ vars.VPC_ID }}
          TF_VAR_subnet_1_id: ${{ vars.PRIVATE_SUBNET_1_ID }}
          TF_VAR_subnet_2_id: ${{ vars.PRIVATE_SUBNET_2_ID }}
          TF_VAR_ecs_security_group_id: ${{ vars.BRANCH_SECURITY_GROUP_ID }}
          TF_VAR_index_name: ${{ needs.extract-branch-names.outputs.db_name }}
          TF_VAR_mongodb_uri: ${{ vars.EPHEMERAL_MONGODB_URI }}
          TF_VAR_mongodb_name: ${{ needs.extract-branch-names.outputs.db_name }}
          TF_VAR_mongodb_username: ${{ secrets.MONGODB_USERNAME }}
          TF_VAR_mongodb_password: ${{ secrets.MONGODB_PASSWORD }}

        run: |
          terraform init -upgrade -backend-config="key=${{ needs.extract-branch-names.outputs.branch_name }}"
          terraform plan -target=module.aws_ecs
          terraform apply -target=module.aws_ecs -auto-approve
      - name: Get API URL
        id: get-api-url
        run: |
          echo "api_url=https://${{ needs.extract-branch-names.outputs.branch_name }}.api.dataherald.ai" >> "$GITHUB_OUTPUT"
      - name: Delete untagged images
        run: |
          # Get untagged images
          UNTAGGED_CORE_IMAGES=$(aws ecr list-images --repository-name $ECR_CORE_REPOSITORY --filter tagStatus=UNTAGGED --query 'imageIds[*]' --region us-east-1 --output json --region us-east-1)
          UNTAGGED_SERVER_IMAGES=$(aws ecr list-images --repository-name $ECR_SERVER_REPOSITORY --filter tagStatus=UNTAGGED --query 'imageIds[*]' --region us-east-1 --output json --region us-east-1)

          # Delete images
          if [ -n "$UNTAGGED_CORE_IMAGES" ] && [ "$UNTAGGED_CORE_IMAGES" != "[]" ]; then
            aws ecr batch-delete-image --repository-name $ECR_CORE_REPOSITORY --image-ids "$UNTAGGED_CORE_IMAGES" --region us-east-1
          fi
          if [ -n "$UNTAGGED_SERVER_IMAGES" ] && [ "$UNTAGGED_SERVER_IMAGES" != "[]" ]; then
            aws ecr batch-delete-image --repository-name $ECR_SERVER_REPOSITORY --image-ids "$UNTAGGED_SERVER_IMAGES" --region us-east-1
          fi
  create-vector-db:
    name: Create PineconeDB
    needs: [extract-branch-names]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/ai/server/terraform/branch
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Apply Terraform
        env:
          TF_VAR_index_name: ${{ needs.extract-branch-names.outputs.db_name }}
        run: |
          terraform init -upgrade -backend-config="key=${{ needs.extract-branch-names.outputs.branch_name }}"
          terraform plan -target=module.pinecone_index
          terraform apply -target=module.pinecone_index -auto-approve
  populate-db:
    name: Populate MongoDB
    needs: [extract-branch-names, start-self-hosted-runner]
    runs-on: ${{ needs.start-self-hosted-runner.outputs.label }}
    defaults:
      run:
        working-directory: ./apps/ai/server
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: true

      - name: Check if MongoDB database exists
        id: db_check
        run: |
          exists=$(mongosh --username ${{ secrets.MONGODB_USERNAME }} --password ${{ secrets.MONGODB_PASSWORD }} "${{ vars.EPHEMERAL_MONGODB_URI }}" --quiet --eval "db.getMongo().getDBNames().includes('${{ needs.extract-branch-names.outputs.db_name }}') ? 'true' : 'false';" | grep -o true || echo "false")
          echo "Branch Database exists: $exists"
          echo "exists=$exists" >> $GITHUB_OUTPUT

        shell: bash

      - name: Restore MongoDB from STAGE dump # ensure there's only one folder in the dump directory
        if: steps.db_check.outputs.exists == 'false' && github.event.inputs.option == 'stage'
        run: |
          echo "Previous step output: ${{ steps.db_check.outputs.exists }}"
          echo "Database does not exist. Restoring from STAGE dump..."
          mongodump --username ${{ secrets.MONGODB_USERNAME }} --password ${{ secrets.MONGODB_PASSWORD }} --uri="${{ vars.STAGING_MONGODB_URI }}"
          cd dump
          from_db=(*)
          mongorestore . --username ${{ secrets.MONGODB_USERNAME }} --password ${{ secrets.MONGODB_PASSWORD }} --nsFrom "$from_db.*" --nsTo "${{ needs.extract-branch-names.outputs.db_name }}.*" --uri="${{ vars.EPHEMERAL_MONGODB_URI }}"
      - name: Restore MongoDB from sample db
        if: steps.db_check.outputs.exists == 'false' && github.event.inputs.option == 'sample'
        run: |
          echo "Previous step output: ${{ steps.db_check.outputs.exists }}"
          echo "Database does not exist. Restoring from SAMPLE dump..."
          cd database/migrations/dump
          from_db=(*)
          mongorestore . --username ${{ secrets.MONGODB_USERNAME }} --password ${{ secrets.MONGODB_PASSWORD }} --nsFrom "$from_db.*" --nsTo "${{ needs.extract-branch-names.outputs.db_name }}.*" --uri="${{ vars.EPHEMERAL_MONGODB_URI }}"
      - name: Create an empty MongoDB database
        if: steps.db_check.outputs.exists == 'false' && github.event.inputs.option == 'empty'
        run: |
          echo "Previous step output: ${{ steps.db_check.outputs.exists }}"
          echo "Database does not exist. Creating an empty database..."
          mongosh --username ${{ secrets.MONGODB_USERNAME }} --password ${{ secrets.MONGODB_PASSWORD }} "${{ vars.EPHEMERAL_MONGODB_URI }}" --eval "db.getSiblingDB('${{ needs.extract-branch-names.outputs.db_name }}').createCollection('empty')"
      - name: Run migration script # liquibase cli and mongo driver already installed in runner
        env:
          LIQUIBASE_COMMAND_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          LIQUIBASE_COMMAND_URL: ${{ vars.EPHEMERAL_MONGODB_URI }}/${{ needs.extract-branch-names.outputs.db_name }}
        run: |
          liquibase --changeLogFile=database/migrations/changelog.yaml update
      - name: Delete DB if failure
        if: failure()
        run: |
          mongosh --username ${{ secrets.MONGODB_USERNAME }} --password ${{ secrets.MONGODB_PASSWORD }} "${{ vars.EPHEMERAL_MONGODB_URI }}" --eval "db.getSiblingDB('${{ needs.extract-branch-names.outputs.db_name }}').dropDatabase()"

  populate-vector-db:
    name: Populate PineconeDB
    needs:
      [
        extract-branch-names,
        start-self-hosted-runner,
        populate-db,
        create-vector-db,
      ]
    runs-on: ${{ needs.start-self-hosted-runner.outputs.label }}
    defaults:
      run:
        working-directory: ./apps/ai/server
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: true
      - name: Populate PineconeDB
        env:
          PINECONE_INDEX_NAME: ${{ needs.extract-branch-names.outputs.db_name }}
          MONGODB_URI: ${{ vars.EPHEMERAL_MONGODB_URI }}
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_NAME: ${{ needs.extract-branch-names.outputs.db_name }}
        run: |
          cd database/scripts/populate_pinecone_db
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt
          python3 -u script.py

  deploy-frontend:
    name: Deploy Frontend
    needs: [extract-branch-names, deploy-backend]
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.console_dns.outputs.url }}
    env:
      VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ vars.VERCEL_AI_CONSOLE_PROJECT_ID }}
      VERCEL_TEAM_NAME: ${{ vars.VERCEL_TEAM_NAME }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Set Console DNS
        id: console_dns
        run: |
          echo "domain=${{ needs.extract-branch-names.outputs.branch_name }}.console.dataherald.ai" >> "$GITHUB_OUTPUT"
          echo "url=https://${{ needs.extract-branch-names.outputs.branch_name }}.console.dataherald.ai" >> "$GITHUB_OUTPUT"
      - name: Deploy to Vercel and set custom domain alias
        run: |
          echo Deploying to Vercel with the following environment variables:
          echo "NEXT_PUBLIC_API_URL=${{ needs.deploy-backend.outputs.api_url }}"
          echo "AUTH0_BASE_URL=${{ steps.console_dns.outputs.url }}"

          vercel deploy --yes --build-env NEXT_PUBLIC_API_URL=${{ needs.deploy-backend.outputs.api_url }} --env AUTH0_BASE_URL=${{ steps.console_dns.outputs.url }} --token=${{ secrets.VERCEL_ACCESS_TOKEN }} >deployment-url.txt 2>error.txt

          # check the exit code
          code=$?
          if [ $code -eq 0 ]; then
              # Now you can use the deployment url from stdout for the next step of your workflow
              deploymentUrl=`cat deployment-url.txt`
              vercel alias set $deploymentUrl ${{ steps.console_dns.outputs.domain }} --scope $VERCEL_TEAM_NAME --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
          else
              # Handle the error
              errorMessage=`cat error.txt`
              echo "There was an error: $errorMessage"
          fi

  send-cancelled-slack-notification:
    name: Send Cancelled Slack Notification
    needs:
      [
        extract-branch-names,
        deploy-backend,
        populate-db,
        populate-vector-db,
        deploy-frontend,
      ]
    if: cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Send cancelled notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.GH_SLACK_WEBHOOK_URL }}
          SLACK_TITLE: Branch Deployment CANCELLED
          SLACK_MESSAGE: |
            The branch environment deployment was cancelled. Please check the GitHub Actions logs for more details.

            *Branch*: `${{ needs.extract-branch-names.outputs.branch }}`

          SLACK_COLOR: cancelled

  send-failure-slack-notification:
    name: Send Failure Slack Notification
    needs:
      [
        extract-branch-names,
        deploy-backend,
        populate-db,
        populate-vector-db,
        deploy-frontend,
      ]
    if: needs.deploy-backend.result == 'failure' || needs.populate-db.result == 'failure' || needs.populate-vector-db.result == 'failure' || needs.deploy-frontend.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Send failed notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.GH_SLACK_WEBHOOK_URL }}
          SLACK_TITLE: Branch Deployment FAILED
          SLACK_MESSAGE: |
            The branch environment deployment failed. Please check the GitHub Actions logs for more details.

            *Branch*: `${{ needs.extract-branch-names.outputs.branch }}`

          SLACK_COLOR: failure

  send-success-slack-notification:
    name: Send Success Slack Notification
    needs:
      [
        extract-branch-names,
        deploy-backend,
        populate-db,
        populate-vector-db,
        deploy-frontend,
      ]
    if: needs.deploy-backend.result == 'success' && needs.populate-db.result == 'success' && needs.populate-vector-db.result == 'success' && needs.deploy-frontend.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Send success notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.GH_SLACK_WEBHOOK_URL }}
          SLACK_TITLE: Branch Deployment SUCCEEDED
          SLACK_MESSAGE: |
            The branch environment deployment succeeded. Here are the details:

            *Branch*: `${{ needs.extract-branch-names.outputs.branch }}`
            *API URL*: ${{ needs.deploy-backend.outputs.api_url }}
            *Console URL*: ${{ needs.deploy-frontend.outputs.url }}
          SLACK_COLOR: success

  stop-self-hosted-runner:
    name: Stop self-hosted EC2 runner
    needs: [start-self-hosted-runner, populate-db, populate-vector-db]
    if: always()
    uses: ./.github/workflows/ai-stop-self-hosted-runner.yml
    secrets: inherit
    with:
      label: ${{ needs.start-self-hosted-runner.outputs.label }}
      ec2_instance_id: ${{ needs.start-self-hosted-runner.outputs.ec2_instance_id }}
