name: AI Deploy STAGE Environment

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ai-deploy-stage-env.yml" # this file
      - ".github/workflows/ai-deploy-env.yml"
      - ".github/workflows/ai-build-docker.yml"
      - ".github/workflows/ai-deploy-docker-ecs.yml"
      - ".github/workflows/ai-deploy-frontend.yml"
      - "apps/ai/**"
      - "!**/.env.example"
      - "!**/README.md"

jobs:
  deploy-env:
    name: Deploy Stage
    uses: ./.github/workflows/ai-deploy-env.yml
    secrets: inherit
    with:
      target_env: stage
