name: AI Deploy PROD Environment

on:
  release:
    types: [published]

jobs:
  deploy-env:
    name: Deploy Production
    uses: ./.github/workflows/ai-deploy-env.yml
    secrets: inherit
    with:
      target_env: prod
