name: Extract Branch Names

on:
  workflow_call:
    outputs:
      branch:
        value: ${{ jobs.extract-branch-names.outputs.branch }}
      branch_name:
        value: ${{ jobs.extract-branch-names.outputs.branch_name }}
      db_name:
        value: ${{ jobs.extract-branch-names.outputs.db_name }}

jobs:
  extract-branch-names:
    name: Setup Names From Branch
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
      branch_name: ${{ steps.extract_branch.outputs.branch_name }}
      db_name: ${{ steps.extract_branch.outputs.db_name }}
    runs-on: ubuntu-latest
    steps:
      - id: extract_branch
        shell: bash
        env:
          RESOURCE_NAME_LENGHT: 32
        run: |
          branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

          ### STRIP "customer/" prefix if exists and format the branch name

          formatted_branch=$(echo "$branch" | tr '[:upper:]' '[:lower:]' | sed 's/^customer\///' | sed 's/[^a-zA-Z0-9]/-/g')
          db_name=$formatted_branch

          # Terraform resources name lenght limit is 32
          # MongoDB database name length limit is 38
          formatted_branch=${formatted_branch:0:${{ env.RESOURCE_NAME_LENGHT }}}
          db_name=${db_name:0:${{ env.RESOURCE_NAME_LENGHT }}} 

          # Ensure the last character is alphanumeric 
          # Pinecone doesn't allow special characters for the last character
          while [[ ! ${formatted_branch: -1} =~ [a-zA-Z0-9] ]]; do
            formatted_branch=${formatted_branch:0:-1}
          done

          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "branch_name=$formatted_branch" >> $GITHUB_OUTPUT
          echo "db_name=$db_name" >> $GITHUB_OUTPUT
