name: AI Server - Quality Checks
on:
  push:
    paths:
      - .github/workflows/ai-server-lint.yml
      - apps/ai/server/**
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/ai/server
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: ./apps/ai/server
      - uses: psf/black@stable
        with:
          src: ./apps/ai/server
