name: AI Start Self-Hosted Runner

on:
  workflow_call:
    outputs:
      label:
        description: "The self hosted github runner label"
        value: ${{ jobs.start-self-hosted-runner.outputs.label }}
      ec2_instance_id:
        description: "The self hosted github runner ec2 instance id"
        value: ${{ jobs.start-self-hosted-runner.outputs.ec2_instance_id }}

jobs:
  start-self-hosted-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2_instance_id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          ec2-image-id: ${{ vars.SELF_HOSTED_RUNNER_IMAGE_ID }}
          ec2-instance-type: t2.micro
          subnet-id: ${{ vars.SELF_HOSTED_RUNNER_SUBNET_ID }} # this is a private subnet, even though the mongo vpce is set for public subnet, it will work, probably because of the route table
          security-group-id: ${{ vars.SELF_HOSTED_RUNNER_SECURITY_GROUP_ID }}
          pre-runner-script: |
            source /etc/profile.d/liquibase.sh
