name: AI Stop Self-Hosted Runner

on:
  workflow_call:
    inputs:
      label:
        description: "The label of the self-hosted runner to start"
        required: true
        type: string
      ec2_instance_id:
        description: "The EC2 instance ID of the self-hosted runner to start"
        required: true
        type: string

env:
  AWS_REGION: us-east-1

jobs:
  stop-self-hosted-runner:
    name: Stop self-hosted EC2 runner
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          label: ${{ inputs.label }}
          ec2-instance-id: ${{ inputs.ec2_instance_id }}
